"""create role table and insert initial roles

Revision ID: 6e0aae0c558f
Revises: 3a53c81fab87
Create Date: 2024-07-24 15:30:20.954534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '6e0aae0c558f'
down_revision = '3a53c81fab87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False)
    )

    op.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM role WHERE id = 1) THEN
                    INSERT INTO role (id, name) VALUES (1, 'admin');
                END IF;

                IF NOT EXISTS (SELECT 1 FROM role WHERE id = 2) THEN
                    INSERT INTO role (id, name) VALUES (2, 'user');
                END IF;

                IF NOT EXISTS (SELECT 1 FROM role WHERE id = 3) THEN
                    INSERT INTO role (id, name) VALUES (3, 'guest');
                END IF;
            END
            $$;
        """)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
